// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AuthGithubCallbackData,
  AuthGithubStartData,
  AuthLogoutData,
  AuthLogoutResponses,
  AuthMeData,
  AuthMeResponses,
  ClearProfileData,
  ClearProfileErrors,
  ClearProfileResponses,
  ConnectReposData,
  ConnectReposErrors,
  ConnectReposResponses,
  DeleteInboxItemData,
  DeleteInboxItemErrors,
  DeleteInboxItemResponses,
  ExtractToneData,
  ExtractToneErrors,
  ExtractToneResponses,
  GetDraftsData,
  GetDraftsErrors,
  GetDraftsResponses,
  GetGithubReposData,
  GetGithubReposErrors,
  GetGithubReposResponses,
  GetInboxData,
  GetInboxErrors,
  GetInboxResponses,
  GetPreferencesData,
  GetPreferencesErrors,
  GetPreferencesResponses,
  GetReposData,
  GetReposErrors,
  GetReposResponses,
  GetRepoTriggerOptionsData,
  GetRepoTriggerOptionsErrors,
  GetRepoTriggerOptionsResponses,
  ToggleRepoAutoGenerateData,
  ToggleRepoAutoGenerateErrors,
  ToggleRepoAutoGenerateResponses,
  TriggerRepoData,
  TriggerRepoErrors,
  TriggerRepoResponses,
  UpdateDraftData,
  UpdateDraftErrors,
  UpdateDraftResponses,
  UpdatePreferencesData,
  UpdatePreferencesErrors,
  UpdatePreferencesResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Start GitHub OAuth flow
 */
export const authGithubStart = <ThrowOnError extends boolean = false>(
  options?: Options<AuthGithubStartData, ThrowOnError>,
) =>
  (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: "/auth/github/start",
    ...options,
  });

/**
 * GitHub OAuth callback
 */
export const authGithubCallback = <ThrowOnError extends boolean = false>(
  options?: Options<AuthGithubCallbackData, ThrowOnError>,
) =>
  (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: "/auth/github/callback",
    ...options,
  });

/**
 * Log out current user
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthLogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<AuthLogoutResponses, unknown, ThrowOnError>({
    url: "/auth/logout",
    ...options,
  });

/**
 * Get current authenticated user
 */
export const authMe = <ThrowOnError extends boolean = false>(
  options?: Options<AuthMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AuthMeResponses, unknown, ThrowOnError>({
    url: "/auth/me",
    ...options,
  });

/**
 * List drafts with pagination
 */
export const getDrafts = <ThrowOnError extends boolean = false>(
  options?: Options<GetDraftsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetDraftsResponses,
    GetDraftsErrors,
    ThrowOnError
  >({ url: "/drafts", ...options });

/**
 * Update a draft
 */
export const updateDraft = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDraftData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UpdateDraftResponses,
    UpdateDraftErrors,
    ThrowOnError
  >({
    url: "/drafts/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List GitHub repositories
 */
export const getGithubRepos = <ThrowOnError extends boolean = false>(
  options?: Options<GetGithubReposData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetGithubReposResponses,
    GetGithubReposErrors,
    ThrowOnError
  >({ url: "/github/repos", ...options });

/**
 * List inbox items with pagination
 */
export const getInbox = <ThrowOnError extends boolean = false>(
  options?: Options<GetInboxData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetInboxResponses,
    GetInboxErrors,
    ThrowOnError
  >({ url: "/inbox", ...options });

/**
 * Delete an inbox item
 */
export const deleteInboxItem = <ThrowOnError extends boolean = false>(
  options: Options<DeleteInboxItemData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteInboxItemResponses,
    DeleteInboxItemErrors,
    ThrowOnError
  >({ url: "/inbox/{id}", ...options });

/**
 * Get user writing preferences
 */
export const getPreferences = <ThrowOnError extends boolean = false>(
  options?: Options<GetPreferencesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetPreferencesResponses,
    GetPreferencesErrors,
    ThrowOnError
  >({ url: "/preferences", ...options });

/**
 * Update user writing preferences
 */
export const updatePreferences = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePreferencesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UpdatePreferencesResponses,
    UpdatePreferencesErrors,
    ThrowOnError
  >({
    url: "/preferences",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Extract tone profile from writing examples
 */
export const extractTone = <ThrowOnError extends boolean = false>(
  options: Options<ExtractToneData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ExtractToneResponses,
    ExtractToneErrors,
    ThrowOnError
  >({
    url: "/preferences/tone-extract",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Clear user profile data
 */
export const clearProfile = <ThrowOnError extends boolean = false>(
  options?: Options<ClearProfileData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    ClearProfileResponses,
    ClearProfileErrors,
    ThrowOnError
  >({ url: "/profile/clear", ...options });

/**
 * List connected repositories with pagination
 */
export const getRepos = <ThrowOnError extends boolean = false>(
  options?: Options<GetReposData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetReposResponses,
    GetReposErrors,
    ThrowOnError
  >({ url: "/repos", ...options });

/**
 * Connect repositories
 */
export const connectRepos = <ThrowOnError extends boolean = false>(
  options: Options<ConnectReposData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ConnectReposResponses,
    ConnectReposErrors,
    ThrowOnError
  >({
    url: "/repos",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get available trigger options for a repository
 */
export const getRepoTriggerOptions = <ThrowOnError extends boolean = false>(
  options: Options<GetRepoTriggerOptionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetRepoTriggerOptionsResponses,
    GetRepoTriggerOptionsErrors,
    ThrowOnError
  >({ url: "/repos/{id}/trigger-options", ...options });

/**
 * Toggle auto-generate for a repository
 */
export const toggleRepoAutoGenerate = <ThrowOnError extends boolean = false>(
  options: Options<ToggleRepoAutoGenerateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ToggleRepoAutoGenerateResponses,
    ToggleRepoAutoGenerateErrors,
    ThrowOnError
  >({
    url: "/repos/{id}/toggle",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Trigger content generation for a repository
 */
export const triggerRepo = <ThrowOnError extends boolean = false>(
  options: Options<TriggerRepoData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TriggerRepoResponses,
    TriggerRepoErrors,
    ThrowOnError
  >({
    url: "/repos/{id}/trigger",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
