// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api` | (string & {});
};

export type User = {
  id?: string;
  githubLogin?: string;
  githubName?: string;
  avatarUrl?: string;
  writingStyle?: string;
};

export type WritingStyle = {
  [key: string]: unknown;
};

export type ToneProfile = {
  [key: string]: unknown;
};

export type RepoOwner = {
  login: string;
};

export type GithubRepo = {
  id?: string;
  full_name?: string;
  name?: string;
  private?: boolean;
  default_branch?: string;
  owner?: RepoOwner;
  html_url?: string;
  connected?: boolean;
};

export type ConnectedRepo = {
  id?: string;
  fullName?: string;
  defaultBranch?: string;
};

export type Draft = {
  [key: string]: unknown;
};

export type InboxItem = {
  [key: string]: unknown;
};

export type PaginationMeta = {
  total: number;
  limit: number;
  offset: number;
  hasMore: boolean;
  nextOffset: number;
};

export type Commit = {
  sha?: string;
  shortSha?: string;
  message?: string;
  author?: string;
  committedAt?: string;
  url?: string;
};

export type ReleaseItem = {
  id?: string;
  tag?: string;
  title?: string;
  url?: string;
} | null;

export type PullRequestItem = {
  prNumber?: number;
  tag?: string;
  title?: string;
  url?: string;
  mergedAt?: string | null;
} | null;

export type TriggerOption = {
  available?: boolean;
  description?: string;
  item?: ReleaseItem | PullRequestItem;
  items?: Array<Commit>;
  maxSelectable?: number;
  error?: string | null;
};

export type TriggerOptions = {
  ok: boolean;
  repo: ConnectedRepo;
  options: {
    auto?: TriggerOption;
    github_release?: TriggerOption;
    merged_pr?: TriggerOption;
    commits?: TriggerOption;
  };
};

export type TriggerSignal = "auto" | "github_release" | "merged_pr" | "commits";

export type Error = {
  error: string;
};

export type AuthGithubStartData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/github/start";
};

export type AuthGithubCallbackData = {
  body?: never;
  path?: never;
  query?: {
    code?: string;
    state?: string;
    error?: string;
  };
  url: "/auth/github/callback";
};

export type AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/logout";
};

export type AuthLogoutResponses = {
  /**
   * Successfully logged out
   */
  200: {
    ok: boolean;
  };
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/me";
};

export type AuthMeResponses = {
  /**
   * Current user info
   */
  200:
    | {
        authenticated: true;
        user: User;
        writingStyles: Array<WritingStyle>;
        connectedRepoCount: number;
      }
    | {
        authenticated: false;
      };
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type GetDraftsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/drafts";
};

export type GetDraftsErrors = {
  /**
   * Not authenticated
   */
  401: Error;
};

export type GetDraftsError = GetDraftsErrors[keyof GetDraftsErrors];

export type GetDraftsResponses = {
  /**
   * Paginated list of drafts
   */
  200: {
    items: Array<Draft>;
    total: number;
    page: number;
    limit: number;
    hasMore: boolean;
  };
};

export type GetDraftsResponse = GetDraftsResponses[keyof GetDraftsResponses];

export type UpdateDraftData = {
  body: {
    [key: string]: unknown;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/drafts/{id}";
};

export type UpdateDraftErrors = {
  /**
   * Bad request
   */
  400: Error;
  /**
   * Not authenticated
   */
  401: Error;
};

export type UpdateDraftError = UpdateDraftErrors[keyof UpdateDraftErrors];

export type UpdateDraftResponses = {
  /**
   * Updated draft
   */
  200: {
    draft: Draft;
  };
};

export type UpdateDraftResponse =
  UpdateDraftResponses[keyof UpdateDraftResponses];

export type GetGithubReposData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
  };
  url: "/github/repos";
};

export type GetGithubReposErrors = {
  /**
   * Bad request
   */
  400: Error;
  /**
   * Not authenticated
   */
  401: Error;
};

export type GetGithubReposError =
  GetGithubReposErrors[keyof GetGithubReposErrors];

export type GetGithubReposResponses = {
  /**
   * List of GitHub repositories
   */
  200: {
    repos: Array<GithubRepo>;
    page: number;
  };
};

export type GetGithubReposResponse =
  GetGithubReposResponses[keyof GetGithubReposResponses];

export type GetInboxData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
  };
  url: "/inbox";
};

export type GetInboxErrors = {
  /**
   * Not authenticated
   */
  401: Error;
};

export type GetInboxError = GetInboxErrors[keyof GetInboxErrors];

export type GetInboxResponses = {
  /**
   * Paginated list of inbox items
   */
  200: {
    items: Array<InboxItem>;
    page: PaginationMeta;
  };
};

export type GetInboxResponse = GetInboxResponses[keyof GetInboxResponses];

export type DeleteInboxItemData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/inbox/{id}";
};

export type DeleteInboxItemErrors = {
  /**
   * Bad request
   */
  400: Error;
  /**
   * Not authenticated
   */
  401: Error;
};

export type DeleteInboxItemError =
  DeleteInboxItemErrors[keyof DeleteInboxItemErrors];

export type DeleteInboxItemResponses = {
  /**
   * Deleted inbox item
   */
  200: {
    ok: boolean;
    deleted: InboxItem;
  };
};

export type DeleteInboxItemResponse =
  DeleteInboxItemResponses[keyof DeleteInboxItemResponses];

export type GetPreferencesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/preferences";
};

export type GetPreferencesErrors = {
  /**
   * Not authenticated
   */
  401: Error;
};

export type GetPreferencesError =
  GetPreferencesErrors[keyof GetPreferencesErrors];

export type GetPreferencesResponses = {
  /**
   * User preferences
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetPreferencesResponse =
  GetPreferencesResponses[keyof GetPreferencesResponses];

export type UpdatePreferencesData = {
  body: {
    newToneProfile?: ToneProfile;
    writingStyle?: string;
  };
  path?: never;
  query?: never;
  url: "/preferences";
};

export type UpdatePreferencesErrors = {
  /**
   * Bad request
   */
  400: Error;
  /**
   * Not authenticated
   */
  401: Error;
};

export type UpdatePreferencesError =
  UpdatePreferencesErrors[keyof UpdatePreferencesErrors];

export type UpdatePreferencesResponses = {
  /**
   * Updated preferences
   */
  200: {
    [key: string]: unknown;
  };
};

export type UpdatePreferencesResponse =
  UpdatePreferencesResponses[keyof UpdatePreferencesResponses];

export type ExtractToneData = {
  body: {
    /**
     * 3-5 example posts as text
     */
    examples: string;
  };
  path?: never;
  query?: never;
  url: "/preferences/tone-extract";
};

export type ExtractToneErrors = {
  /**
   * Bad request
   */
  400: Error;
  /**
   * Not authenticated
   */
  401: Error;
};

export type ExtractToneError = ExtractToneErrors[keyof ExtractToneErrors];

export type ExtractToneResponses = {
  /**
   * Extracted tone profile
   */
  200: {
    ok: boolean;
    suggestedTone: string;
    meta: {
      exampleCount?: number;
    };
  };
};

export type ExtractToneResponse =
  ExtractToneResponses[keyof ExtractToneResponses];

export type ClearProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/profile/clear";
};

export type ClearProfileErrors = {
  /**
   * Bad request
   */
  400: Error;
  /**
   * Not authenticated
   */
  401: Error;
};

export type ClearProfileError = ClearProfileErrors[keyof ClearProfileErrors];

export type ClearProfileResponses = {
  /**
   * Profile cleared
   */
  200: {
    ok: boolean;
    cleared: {
      [key: string]: unknown;
    };
  };
};

export type ClearProfileResponse =
  ClearProfileResponses[keyof ClearProfileResponses];

export type GetReposData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/repos";
};

export type GetReposErrors = {
  /**
   * Not authenticated
   */
  401: Error;
};

export type GetReposError = GetReposErrors[keyof GetReposErrors];

export type GetReposResponses = {
  /**
   * Paginated list of connected repositories
   */
  200: {
    items: Array<ConnectedRepo>;
    total: number;
    page: number;
    limit: number;
    hasMore: boolean;
  };
};

export type GetReposResponse = GetReposResponses[keyof GetReposResponses];

export type ConnectReposData = {
  body: {
    selectedRepos: Array<{
      id: string;
      full_name: string;
      name: string;
      private: boolean;
      default_branch: string;
      owner: RepoOwner;
      autoGenerate?: boolean;
    }>;
  };
  path?: never;
  query?: never;
  url: "/repos";
};

export type ConnectReposErrors = {
  /**
   * Bad request
   */
  400: Error;
  /**
   * Not authenticated
   */
  401: Error;
};

export type ConnectReposError = ConnectReposErrors[keyof ConnectReposErrors];

export type ConnectReposResponses = {
  /**
   * Connected repositories
   */
  200: {
    repos: Array<ConnectedRepo>;
  };
};

export type ConnectReposResponse =
  ConnectReposResponses[keyof ConnectReposResponses];

export type GetRepoTriggerOptionsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/repos/{id}/trigger-options";
};

export type GetRepoTriggerOptionsErrors = {
  /**
   * Not authenticated
   */
  401: Error;
  /**
   * Repository not found
   */
  404: Error;
};

export type GetRepoTriggerOptionsError =
  GetRepoTriggerOptionsErrors[keyof GetRepoTriggerOptionsErrors];

export type GetRepoTriggerOptionsResponses = {
  /**
   * Available trigger options
   */
  200: TriggerOptions;
};

export type GetRepoTriggerOptionsResponse =
  GetRepoTriggerOptionsResponses[keyof GetRepoTriggerOptionsResponses];

export type ToggleRepoAutoGenerateData = {
  body: {
    autoGenerate: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/repos/{id}/toggle";
};

export type ToggleRepoAutoGenerateErrors = {
  /**
   * Bad request
   */
  400: Error;
  /**
   * Not authenticated
   */
  401: Error;
};

export type ToggleRepoAutoGenerateError =
  ToggleRepoAutoGenerateErrors[keyof ToggleRepoAutoGenerateErrors];

export type ToggleRepoAutoGenerateResponses = {
  /**
   * Updated repository
   */
  200: {
    repo: ConnectedRepo;
  };
};

export type ToggleRepoAutoGenerateResponse =
  ToggleRepoAutoGenerateResponses[keyof ToggleRepoAutoGenerateResponses];

export type TriggerRepoData = {
  body: {
    signal?: TriggerSignal;
    /**
     * Required when signal is merged_pr
     */
    prNumber?: number;
    /**
     * Required when signal is commits
     */
    commitShas?: Array<string>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/repos/{id}/trigger";
};

export type TriggerRepoErrors = {
  /**
   * Bad request
   */
  400: Error;
  /**
   * Not authenticated
   */
  401: Error;
  /**
   * Repository not found
   */
  404: Error;
};

export type TriggerRepoError = TriggerRepoErrors[keyof TriggerRepoErrors];

export type TriggerRepoResponses = {
  /**
   * Trigger result
   */
  200:
    | {
        ok: true;
        signal: string;
        repo: ConnectedRepo;
        run: {
          [key: string]: unknown;
        };
        draft: Draft;
        inboxItem: InboxItem;
      }
    | {
        ok: false;
        error: string;
        repo: ConnectedRepo;
        run: {
          [key: string]: unknown;
        };
      };
};

export type TriggerRepoResponse =
  TriggerRepoResponses[keyof TriggerRepoResponses];
